---
- name: Check dockerd bin
  stat:
    path: "{{ path_to_docker_bin }}"
  register: check_docker_bin

- name: Install docker-ce
  become: yes
  block:
    - name: Get script for install docker
      get_url:
        url: "{{ url_script_docker }}"
        dest: "{{ path_to_script_docker_install }}"

    - name: Install docker
      command: "sh {{ path_to_script_docker_install }}"
  when: not check_docker_bin.stat.exists
